### ISSUE TITLE
这个python 脚本启不来，需要配啥

### ISSUE THREAD

**Issue by Armor-cn** [sxysxy/SXYWeChatBot#2]
![1688274887530](https://github.com/sxysxy/SXYWeChatBot/assets/31821714/2156f0e8-51c2-46d6-8cfe-fdfbd07aa6e3)

**Comment by sxysxy** [comment]
Andite/anything-v4.0 这个模型被删除了，我在发布这个仓库的时候还有，现在网上现在没有了，只能转一个模型了，你看config.json里面，把Diffusion模型换成比如
```
runwayml/stable-diffusion-v1-5
```

**Comment by Armor-cn** [comment]
这东西也太大了吧，5G
![1688276180309](https://github.com/sxysxy/SXYWeChatBot/assets/31821714/c896c520-8ac6-4563-a60d-026c02c904d4)

**Comment by sxysxy** [comment]
= = 这玩意训练的时候可是用了256块A100训练好久的

**Comment by sxysxy** [comment]
另外ChatGPT目前也不好使了，OpenAI的免费额度用完了，国内办的visa卡也无法给OpenAI充值。可以看看清湖大学开源的ChatGLM2，在中文C-EVAL评测上超过了OpenAI GPT4
